var base_map_names = [
	"Crypt Map",
	"Desert Map",
	"Dunes Map",
	"Dungeon Map",
	"Grotto Map",
	"Pit Map",
	"Tropical Island Map",
	"Arcade Map",
	"Cemetery Map",
	"Channel Map",
	"Mountain Ledge Map",
	"Sewer Map",
	"Thicket Map",
	"Wharf Map",
	"Ghetto Map",
	"Mud Geyser Map",
	"Museum Map",
	"Quarry Map",
	"Reef Map",
	"Spider Lair Map",
	"Vaal Pyramid Map",
	"Arena Map",
	"Overgrown Shrine Map",
	"Promenade Map",
	"Phantasmagoria Map",
	"Shore Map",
	"Spider Forest Map",
	"Tunnel Map",
	"Bog Map",
	"Coves Map",
	"Graveyard Map",
	"Pier Map",
	"Underground Sea Map",
	"Villa Map",
	"Arachnid Nest Map",
	"Catacomb Map",
	"Colonnade Map",
	"Dry Woods Map",
	"Strand Map",
	"Vaal Temple Map", // Tier: 14 (81) 
	"Temple Map",
	"Jungle Valley Map",
	"Terrace Map",
	"Mine Map",
	"Torture Chamber Map",
	"Waste Pool Map",
	"Canyon Map",
	"Cells Map",
	"Dark Forest Map",
	"Dry Peninsula Map",
	"Orchard Map",
	"Arid Lake Map",
	"Gorge Map",
	"Malformation Map",
	"Residence Map",
	"Underground River Map",
	"Bazaar Map",
	"Necropolis Map",
	"Plateau Map",
	"Volcano Map",
	"Academy Map",
	"Crematorium Map",
	"Precinct Map",
	"Springs Map",
	"Arsenal Map",
	"Overgrown Ruin Map",
	"Shipyard Map",
	"Village Ruin Map",
	"Courtyard Map",
	"Excavation Map",
	"Wasteland Map",
	"Waterways Map",
	"Conservatory Map",
	"Palace Map",
	"Shrine Map",
	"Abyss Map",
	"Colosseum Map",
	"Core Map"
];
var unique_map_names = [
	"The Coward's Trial",
	"Untainted Paradise",
	"Maelström of Chaos",
	"Mao Kun",
	"Vaults of Atziri",
	"Acton's Nightmare",
	"Hall of Grandmasters",
	"Olmec's Sanctum",
	"Whakawairua Tuahu",
	"Poorjoy's Asylum",
	"Oba's Cursed Trove",
	"Death and Taxes",
];