# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(334, 290)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(About.sizePolicy().hasHeightForWidth())
        About.setSizePolicy(sizePolicy)
        About.setBaseSize(QtCore.QSize(0, 0))
        self.buttonBox = QtWidgets.QDialogButtonBox(About)
        self.buttonBox.setGeometry(QtCore.QRect(10, 250, 321, 41))
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.title = QtWidgets.QLabel(About)
        self.title.setGeometry(QtCore.QRect(10, 0, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.version = QtWidgets.QLabel(About)
        self.version.setGeometry(QtCore.QRect(10, 30, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.version.setFont(font)
        self.version.setAlignment(QtCore.Qt.AlignCenter)
        self.version.setObjectName("version")
        self.shortcuts = QtWidgets.QTableWidget(About)
        self.shortcuts.setGeometry(QtCore.QRect(10, 70, 314, 113))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.shortcuts.setFont(font)
        self.shortcuts.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shortcuts.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.shortcuts.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shortcuts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.shortcuts.setLineWidth(1)
        self.shortcuts.setMidLineWidth(0)
        self.shortcuts.setAutoScroll(False)
        self.shortcuts.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.shortcuts.setTabKeyNavigation(False)
        self.shortcuts.setProperty("showDropIndicator", False)
        self.shortcuts.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.shortcuts.setShowGrid(False)
        self.shortcuts.setGridStyle(QtCore.Qt.NoPen)
        self.shortcuts.setWordWrap(True)
        self.shortcuts.setCornerButtonEnabled(True)
        self.shortcuts.setRowCount(7)
        self.shortcuts.setColumnCount(4)
        self.shortcuts.setObjectName("shortcuts")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(5)
        item.setFont(font)
        self.shortcuts.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shortcuts.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.shortcuts.setItem(6, 3, item)
        self.shortcuts.horizontalHeader().setVisible(True)
        self.shortcuts.horizontalHeader().setCascadingSectionResizes(False)
        self.shortcuts.horizontalHeader().setDefaultSectionSize(78)
        self.shortcuts.horizontalHeader().setHighlightSections(True)
        self.shortcuts.horizontalHeader().setMinimumSectionSize(25)
        self.shortcuts.horizontalHeader().setSortIndicatorShown(False)
        self.shortcuts.verticalHeader().setVisible(False)
        self.shortcuts.verticalHeader().setDefaultSectionSize(13)
        self.shortcuts.verticalHeader().setMinimumSectionSize(20)
        self.update = QtWidgets.QLabel(About)
        self.update.setGeometry(QtCore.QRect(225, 230, 111, 16))
        self.update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update.setAlignment(QtCore.Qt.AlignCenter)
        self.update.setObjectName("update")
        self.label_4 = QtWidgets.QLabel(About)
        self.label_4.setGeometry(QtCore.QRect(8, 190, 141, 21))
        self.label_4.setObjectName("label_4")
        self.email = QtWidgets.QLabel(About)
        self.email.setGeometry(QtCore.QRect(10, 210, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.email.setObjectName("email")
        self.ign = QtWidgets.QLabel(About)
        self.ign.setGeometry(QtCore.QRect(10, 230, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ign.setFont(font)
        self.ign.setObjectName("ign")
        self.label_7 = QtWidgets.QLabel(About)
        self.label_7.setGeometry(QtCore.QRect(9, 50, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.title.setText(_translate("About", "Map Watch"))
        self.version.setText(_translate("About", "Version 1.0"))
        item = self.shortcuts.horizontalHeaderItem(0)
        item.setText(_translate("About", "Action"))
        item = self.shortcuts.horizontalHeaderItem(1)
        item.setText(_translate("About", "Shortcut"))
        item = self.shortcuts.horizontalHeaderItem(2)
        item.setText(_translate("About", "Action"))
        item = self.shortcuts.horizontalHeaderItem(3)
        item.setText(_translate("About", "Shortcut"))
        __sortingEnabled = self.shortcuts.isSortingEnabled()
        self.shortcuts.setSortingEnabled(False)
        item = self.shortcuts.item(0, 0)
        item.setText(_translate("About", "Add"))
        item = self.shortcuts.item(0, 1)
        item.setText(_translate("About", "A"))
        item = self.shortcuts.item(0, 2)
        item.setText(_translate("About", "Minimize"))
        item = self.shortcuts.item(0, 3)
        item.setText(_translate("About", "M"))
        item = self.shortcuts.item(1, 0)
        item.setText(_translate("About", "Add Unlinked Map"))
        item = self.shortcuts.item(1, 1)
        item.setText(_translate("About", "Ctrl + U"))
        item = self.shortcuts.item(1, 2)
        item.setText(_translate("About", "New DB File"))
        item = self.shortcuts.item(1, 3)
        item.setText(_translate("About", "F1"))
        item = self.shortcuts.item(2, 0)
        item.setText(_translate("About", "Remove Map"))
        item = self.shortcuts.item(2, 1)
        item.setText(_translate("About", "Ctrl + D"))
        item = self.shortcuts.item(2, 2)
        item.setText(_translate("About", "Load DB File"))
        item = self.shortcuts.item(2, 3)
        item.setText(_translate("About", "F2"))
        item = self.shortcuts.item(3, 0)
        item.setText(_translate("About", "Clear Map"))
        item = self.shortcuts.item(3, 1)
        item.setText(_translate("About", "Ctrl + X"))
        item = self.shortcuts.item(3, 2)
        item.setText(_translate("About", "Open Stat File"))
        item = self.shortcuts.item(3, 3)
        item.setText(_translate("About", "F3"))
        item = self.shortcuts.item(4, 0)
        item.setText(_translate("About", "Run Map"))
        item = self.shortcuts.item(4, 1)
        item.setText(_translate("About", "Ctrl + R"))
        item = self.shortcuts.item(4, 2)
        item.setText(_translate("About", "Preferences"))
        item = self.shortcuts.item(4, 3)
        item.setText(_translate("About", "F4"))
        item = self.shortcuts.item(5, 0)
        item.setText(_translate("About", "Focus Zana Mods"))
        item = self.shortcuts.item(5, 1)
        item.setText(_translate("About", "Z"))
        item = self.shortcuts.item(5, 2)
        item.setText(_translate("About", "About"))
        item = self.shortcuts.item(5, 3)
        item.setText(_translate("About", "F5"))
        item = self.shortcuts.item(6, 0)
        item.setText(_translate("About", "Focus Bonus IQ"))
        item = self.shortcuts.item(6, 1)
        item.setText(_translate("About", "Q"))
        item = self.shortcuts.item(6, 2)
        item.setText(_translate("About", "Exit"))
        item = self.shortcuts.item(6, 3)
        item.setText(_translate("About", "F12"))
        self.shortcuts.setSortingEnabled(__sortingEnabled)
        self.update.setText(_translate("About", "<html><head/><body><p><span style=\" text-decoration: underline; color:#0055ff;\">Check for Update</span></p></body></html>"))
        self.label_4.setText(_translate("About", "Created by:"))
        self.email.setText(_translate("About", "<html><head/><body><p><span style=\" color:#0055ff;\">Jonathan.D.Hatten@gmail.com</span></p></body></html>"))
        self.ign.setText(_translate("About", "IGN: Grahf_Azura"))
        self.label_7.setText(_translate("About", "Shortcut Keys:"))

