# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addmore.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddMore(object):
    def setupUi(self, AddMore):
        AddMore.setObjectName("AddMore")
        AddMore.resize(341, 320)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddMore)
        self.buttonBox.setGeometry(QtCore.QRect(10, 286, 321, 30))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.unid_data = QtWidgets.QGroupBox(AddMore)
        self.unid_data.setGeometry(QtCore.QRect(10, 5, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.unid_data.setFont(font)
        self.unid_data.setObjectName("unid_data")
        self.add_pack_size = QtWidgets.QSpinBox(self.unid_data)
        self.add_pack_size.setGeometry(QtCore.QRect(120, 50, 42, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.add_pack_size.setFont(font)
        self.add_pack_size.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_pack_size.setReadOnly(False)
        self.add_pack_size.setKeyboardTracking(True)
        self.add_pack_size.setProperty("showGroupSeparator", False)
        self.add_pack_size.setMaximum(100)
        self.add_pack_size.setSingleStep(1)
        self.add_pack_size.setObjectName("add_pack_size")
        self.label_16 = QtWidgets.QLabel(self.unid_data)
        self.label_16.setGeometry(QtCore.QRect(10, 50, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.add_iq = QtWidgets.QSpinBox(self.unid_data)
        self.add_iq.setGeometry(QtCore.QRect(120, 20, 42, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.add_iq.setFont(font)
        self.add_iq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_iq.setReadOnly(False)
        self.add_iq.setKeyboardTracking(True)
        self.add_iq.setProperty("showGroupSeparator", False)
        self.add_iq.setMinimum(30)
        self.add_iq.setMaximum(500)
        self.add_iq.setSingleStep(1)
        self.add_iq.setObjectName("add_iq")
        self.label_15 = QtWidgets.QLabel(self.unid_data)
        self.label_15.setGeometry(QtCore.QRect(170, 20, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.add_ir = QtWidgets.QSpinBox(self.unid_data)
        self.add_ir.setGeometry(QtCore.QRect(270, 20, 42, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.add_ir.setFont(font)
        self.add_ir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_ir.setReadOnly(False)
        self.add_ir.setKeyboardTracking(True)
        self.add_ir.setProperty("showGroupSeparator", False)
        self.add_ir.setMaximum(500)
        self.add_ir.setSingleStep(1)
        self.add_ir.setObjectName("add_ir")
        self.label_14 = QtWidgets.QLabel(self.unid_data)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.unid_data)
        self.label_18.setGeometry(QtCore.QRect(170, 50, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.add_fragments = QtWidgets.QSpinBox(self.unid_data)
        self.add_fragments.setGeometry(QtCore.QRect(270, 50, 42, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.add_fragments.setFont(font)
        self.add_fragments.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_fragments.setReadOnly(False)
        self.add_fragments.setKeyboardTracking(True)
        self.add_fragments.setProperty("showGroupSeparator", False)
        self.add_fragments.setMaximum(3)
        self.add_fragments.setSingleStep(1)
        self.add_fragments.setObjectName("add_fragments")
        self.other_data = QtWidgets.QGroupBox(AddMore)
        self.other_data.setGeometry(QtCore.QRect(10, 90, 321, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.other_data.setFont(font)
        self.other_data.setFlat(False)
        self.other_data.setCheckable(False)
        self.other_data.setObjectName("other_data")
        self.zana_box = QtWidgets.QCheckBox(self.other_data)
        self.zana_box.setGeometry(QtCore.QRect(186, 80, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.zana_box.setFont(font)
        self.zana_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zana_box.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.zana_box.setChecked(False)
        self.zana_box.setObjectName("zana_box")
        self.carto_box = QtWidgets.QCheckBox(self.other_data)
        self.carto_box.setGeometry(QtCore.QRect(10, 80, 161, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.carto_box.setFont(font)
        self.carto_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.carto_box.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.carto_box.setChecked(False)
        self.carto_box.setObjectName("carto_box")
        self.map_notes = QtWidgets.QPlainTextEdit(self.other_data)
        self.map_notes.setGeometry(QtCore.QRect(10, 107, 301, 75))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.map_notes.setFont(font)
        self.map_notes.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.map_notes.setPlainText("")
        self.map_notes.setObjectName("map_notes")
        self.add_zana_mod = QtWidgets.QComboBox(self.other_data)
        self.add_zana_mod.setGeometry(QtCore.QRect(100, 50, 201, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.add_zana_mod.setFont(font)
        self.add_zana_mod.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_zana_mod.setObjectName("add_zana_mod")
        self.label_17 = QtWidgets.QLabel(self.other_data)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.other_data)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.add_league = QtWidgets.QComboBox(self.other_data)
        self.add_league.setGeometry(QtCore.QRect(100, 20, 201, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.add_league.setFont(font)
        self.add_league.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_league.setObjectName("add_league")

        self.retranslateUi(AddMore)
        self.buttonBox.accepted.connect(AddMore.accept)
        self.buttonBox.rejected.connect(AddMore.reject)
        QtCore.QMetaObject.connectSlotsByName(AddMore)

    def retranslateUi(self, AddMore):
        _translate = QtCore.QCoreApplication.translate
        AddMore.setWindowTitle(_translate("AddMore", "Add More Map Data"))
        self.unid_data.setTitle(_translate("AddMore", "Enter Modified Map Data"))
        self.label_16.setToolTip(_translate("AddMore", "<html><head/><body><p>Enter the Pack Size number found inside an unidentified map here.</p></body></html>"))
        self.label_16.setText(_translate("AddMore", "Pack Size:"))
        self.label_15.setToolTip(_translate("AddMore", "<html><head/><body><p>Enter the IR number found inside an unidentified map here.</p></body></html>"))
        self.label_15.setText(_translate("AddMore", "Increased Rarity:"))
        self.label_14.setToolTip(_translate("AddMore", "<html><head/><body><p>Enter the IQ number found inside an unidentified map here.</p></body></html>"))
        self.label_14.setText(_translate("AddMore", "Increased Quantity:"))
        self.label_18.setToolTip(_translate("AddMore", "<html><head/><body><p>Note: If the map is unidentified you don\'t need to enter map fragments (bonus IQ) here since it will be represented in the IQ number in map.  So just enter that IQ.</p></body></html>"))
        self.label_18.setText(_translate("AddMore", "Map Fragments:"))
        self.other_data.setTitle(_translate("AddMore", "Enter Other Map Data"))
        self.zana_box.setText(_translate("AddMore", "Found Master Zana:"))
        self.carto_box.setText(_translate("AddMore", "Found a Cartographer\'s Box:"))
        self.map_notes.setWhatsThis(_translate("AddMore", "<html><head/><body><p><br/></p></body></html>"))
        self.map_notes.setPlaceholderText(_translate("AddMore", "Enter any other notes about the currently running map here."))
        self.label_17.setText(_translate("AddMore", "Add Zana Mod:"))
        self.label_19.setText(_translate("AddMore", "Current League:"))

