# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(400, 225)
        self.label_4 = QtWidgets.QLabel(Preferences)
        self.label_4.setGeometry(QtCore.QRect(16, 110, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.pref_interval = QtWidgets.QSpinBox(Preferences)
        self.pref_interval.setGeometry(QtCore.QRect(170, 50, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pref_interval.setFont(font)
        self.pref_interval.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pref_interval.setMinimum(1)
        self.pref_interval.setMaximum(5)
        self.pref_interval.setProperty("value", 3)
        self.pref_interval.setObjectName("pref_interval")
        self.pref_lang = QtWidgets.QComboBox(Preferences)
        self.pref_lang.setGeometry(QtCore.QRect(170, 110, 131, 21))
        self.pref_lang.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pref_lang.setObjectName("pref_lang")
        self.pref_lang.addItem("")
        self.label_2 = QtWidgets.QLabel(Preferences)
        self.label_2.setGeometry(QtCore.QRect(216, 50, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pref_db_path = QtWidgets.QLineEdit(Preferences)
        self.pref_db_path.setGeometry(QtCore.QRect(196, 80, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pref_db_path.setFont(font)
        self.pref_db_path.setText("")
        self.pref_db_path.setReadOnly(True)
        self.pref_db_path.setObjectName("pref_db_path")
        self.label = QtWidgets.QLabel(Preferences)
        self.label.setGeometry(QtCore.QRect(16, 50, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Preferences)
        self.label_3.setGeometry(QtCore.QRect(6, 10, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Preferences)
        self.label_5.setGeometry(QtCore.QRect(16, 140, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(Preferences)
        self.line.setGeometry(QtCore.QRect(5, 30, 388, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pref_startup = QtWidgets.QCheckBox(Preferences)
        self.pref_startup.setGeometry(QtCore.QRect(-4, 80, 187, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pref_startup.setFont(font)
        self.pref_startup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pref_startup.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pref_startup.setChecked(True)
        self.pref_startup.setObjectName("pref_startup")
        self.pref_statistics = QtWidgets.QComboBox(Preferences)
        self.pref_statistics.setGeometry(QtCore.QRect(170, 140, 131, 21))
        self.pref_statistics.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pref_statistics.setCurrentText("")
        self.pref_statistics.setObjectName("pref_statistics")
        self.buttonBox = QtWidgets.QDialogButtonBox(Preferences)
        self.buttonBox.setGeometry(QtCore.QRect(10, 190, 381, 23))
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.RestoreDefaults|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.line_2 = QtWidgets.QFrame(Preferences)
        self.line_2.setGeometry(QtCore.QRect(5, 170, 388, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(Preferences)
        self.pref_statistics.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "Preferences"))
        self.label_4.setText(_translate("Preferences", "Selected Language:"))
        self.pref_lang.setCurrentText(_translate("Preferences", "English"))
        self.pref_lang.setItemText(0, _translate("Preferences", "English"))
        self.label_2.setText(_translate("Preferences", "seconds"))
        self.label.setText(_translate("Preferences", "Check for maps every:"))
        self.label_3.setText(_translate("Preferences", "Map Watch Preferences"))
        self.label_5.setText(_translate("Preferences", "Selected Statistics File:"))
        self.pref_startup.setText(_translate("Preferences", "Load Database on Startup:  "))

