# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 413)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.map_selected = QtWidgets.QGroupBox(self.centralwidget)
        self.map_selected.setEnabled(True)
        self.map_selected.setGeometry(QtCore.QRect(0, -10, 471, 191))
        font = QtGui.QFont()
        font.setKerning(True)
        self.map_selected.setFont(font)
        self.map_selected.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.map_selected.setTitle("")
        self.map_selected.setFlat(True)
        self.map_selected.setObjectName("map_selected")
        self.label = QtWidgets.QLabel(self.map_selected)
        self.label.setGeometry(QtCore.QRect(10, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.ms_mods = QtWidgets.QTextBrowser(self.map_selected)
        self.ms_mods.setGeometry(QtCore.QRect(162, 50, 301, 102))
        self.ms_mods.setAcceptRichText(True)
        self.ms_mods.setObjectName("ms_mods")
        self.label_2 = QtWidgets.QLabel(self.map_selected)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.map_selected)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.map_selected)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.map_selected)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 71, 16))
        self.label_5.setObjectName("label_5")
        self.ms_name = QtWidgets.QLabel(self.map_selected)
        self.ms_name.setGeometry(QtCore.QRect(170, 20, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ms_name.setFont(font)
        self.ms_name.setStyleSheet("color: rgb(0, 0, 0);")
        self.ms_name.setObjectName("ms_name")
        self.ms_add_map = QtWidgets.QPushButton(self.map_selected)
        self.ms_add_map.setGeometry(QtCore.QRect(260, 160, 201, 23))
        self.ms_add_map.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ms_add_map.setObjectName("ms_add_map")
        self.ms_remove_map = QtWidgets.QPushButton(self.map_selected)
        self.ms_remove_map.setGeometry(QtCore.QRect(10, 160, 201, 23))
        self.ms_remove_map.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ms_remove_map.setObjectName("ms_remove_map")
        self.ms_tier = QtWidgets.QLabel(self.map_selected)
        self.ms_tier.setGeometry(QtCore.QRect(100, 50, 41, 16))
        self.ms_tier.setObjectName("ms_tier")
        self.ms_iq = QtWidgets.QLabel(self.map_selected)
        self.ms_iq.setGeometry(QtCore.QRect(100, 70, 41, 16))
        self.ms_iq.setObjectName("ms_iq")
        self.ms_ir = QtWidgets.QLabel(self.map_selected)
        self.ms_ir.setGeometry(QtCore.QRect(100, 90, 41, 16))
        self.ms_ir.setObjectName("ms_ir")
        self.ms_pack_size = QtWidgets.QLabel(self.map_selected)
        self.ms_pack_size.setGeometry(QtCore.QRect(100, 110, 41, 16))
        self.ms_pack_size.setObjectName("ms_pack_size")
        self.label_11 = QtWidgets.QLabel(self.map_selected)
        self.label_11.setGeometry(QtCore.QRect(20, 130, 71, 16))
        self.label_11.setObjectName("label_11")
        self.ms_rarity = QtWidgets.QLabel(self.map_selected)
        self.ms_rarity.setGeometry(QtCore.QRect(100, 130, 41, 16))
        self.ms_rarity.setText("")
        self.ms_rarity.setObjectName("ms_rarity")
        self.ms_time_stamp = QtWidgets.QLabel(self.map_selected)
        self.ms_time_stamp.setGeometry(QtCore.QRect(390, 10, 81, 16))
        self.ms_time_stamp.setObjectName("ms_time_stamp")
        self.label_13 = QtWidgets.QLabel(self.map_selected)
        self.label_13.setGeometry(QtCore.QRect(290, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.map_running = QtWidgets.QGroupBox(self.centralwidget)
        self.map_running.setGeometry(QtCore.QRect(0, 180, 471, 211))
        self.map_running.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.map_running.setToolTip("")
        self.map_running.setTitle("")
        self.map_running.setFlat(True)
        self.map_running.setObjectName("map_running")
        self.label_6 = QtWidgets.QLabel(self.map_running)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.mr_mods = QtWidgets.QTextBrowser(self.map_running)
        self.mr_mods.setGeometry(QtCore.QRect(162, 39, 301, 102))
        self.mr_mods.setAcceptRichText(False)
        self.mr_mods.setOpenLinks(False)
        self.mr_mods.setObjectName("mr_mods")
        self.label_7 = QtWidgets.QLabel(self.map_running)
        self.label_7.setEnabled(True)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.map_running)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.map_running)
        self.label_9.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.map_running)
        self.label_10.setGeometry(QtCore.QRect(20, 100, 71, 16))
        self.label_10.setObjectName("label_10")
        self.mr_name = QtWidgets.QLabel(self.map_running)
        self.mr_name.setGeometry(QtCore.QRect(170, 10, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mr_name.setFont(font)
        self.mr_name.setStyleSheet("color: rgb(0, 0, 0);")
        self.mr_name.setObjectName("mr_name")
        self.mr_clear_map = QtWidgets.QPushButton(self.map_running)
        self.mr_clear_map.setGeometry(QtCore.QRect(10, 180, 201, 23))
        self.mr_clear_map.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mr_clear_map.setObjectName("mr_clear_map")
        self.mr_run_map = QtWidgets.QPushButton(self.map_running)
        self.mr_run_map.setGeometry(QtCore.QRect(260, 180, 201, 23))
        self.mr_run_map.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mr_run_map.setObjectName("mr_run_map")
        self.mr_ir = QtWidgets.QLabel(self.map_running)
        self.mr_ir.setGeometry(QtCore.QRect(100, 80, 41, 16))
        self.mr_ir.setObjectName("mr_ir")
        self.mr_iq = QtWidgets.QLabel(self.map_running)
        self.mr_iq.setGeometry(QtCore.QRect(100, 60, 31, 16))
        self.mr_iq.setObjectName("mr_iq")
        self.mr_tier = QtWidgets.QLabel(self.map_running)
        self.mr_tier.setGeometry(QtCore.QRect(100, 40, 41, 16))
        self.mr_tier.setObjectName("mr_tier")
        self.mr_pack_size = QtWidgets.QLabel(self.map_running)
        self.mr_pack_size.setGeometry(QtCore.QRect(100, 100, 41, 16))
        self.mr_pack_size.setObjectName("mr_pack_size")
        self.label_12 = QtWidgets.QLabel(self.map_running)
        self.label_12.setGeometry(QtCore.QRect(20, 120, 71, 16))
        self.label_12.setObjectName("label_12")
        self.mr_rarity = QtWidgets.QLabel(self.map_running)
        self.mr_rarity.setGeometry(QtCore.QRect(100, 120, 41, 16))
        self.mr_rarity.setText("")
        self.mr_rarity.setObjectName("mr_rarity")
        self.mr_add_zana_mod = QtWidgets.QComboBox(self.map_running)
        self.mr_add_zana_mod.setGeometry(QtCore.QRect(100, 150, 201, 23))
        self.mr_add_zana_mod.setObjectName("mr_add_zana_mod")
        self.mr_add_bonus_iq = QtWidgets.QSpinBox(self.map_running)
        self.mr_add_bonus_iq.setGeometry(QtCore.QRect(420, 150, 42, 23))
        self.mr_add_bonus_iq.setReadOnly(False)
        self.mr_add_bonus_iq.setKeyboardTracking(True)
        self.mr_add_bonus_iq.setProperty("showGroupSeparator", False)
        self.mr_add_bonus_iq.setMaximum(15)
        self.mr_add_bonus_iq.setSingleStep(5)
        self.mr_add_bonus_iq.setObjectName("mr_add_bonus_iq")
        self.mr_bonus_iq = QtWidgets.QLabel(self.map_running)
        self.mr_bonus_iq.setGeometry(QtCore.QRect(130, 60, 31, 16))
        self.mr_bonus_iq.setText("")
        self.mr_bonus_iq.setObjectName("mr_bonus_iq")
        self.label_14 = QtWidgets.QLabel(self.map_running)
        self.label_14.setGeometry(QtCore.QRect(310, 152, 101, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.map_running)
        self.label_15.setGeometry(QtCore.QRect(20, 152, 81, 16))
        self.label_15.setObjectName("label_15")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 471, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menubar)
        self.menu_create_new_db = QtWidgets.QAction(MainWindow)
        self.menu_create_new_db.setCheckable(False)
        self.menu_create_new_db.setObjectName("menu_create_new_db")
        self.menu_load_db = QtWidgets.QAction(MainWindow)
        self.menu_load_db.setObjectName("menu_load_db")
        self.menu_exit_app = QtWidgets.QAction(MainWindow)
        self.menu_exit_app.setObjectName("menu_exit_app")
        self.menu_preferences = QtWidgets.QAction(MainWindow)
        self.menu_preferences.setObjectName("menu_preferences")
        self.menu_about = QtWidgets.QAction(MainWindow)
        self.menu_about.setObjectName("menu_about")
        self.menu_ms_add_unlinked_map = QtWidgets.QAction(MainWindow)
        self.menu_ms_add_unlinked_map.setObjectName("menu_ms_add_unlinked_map")
        self.menu_ms_add_map = QtWidgets.QAction(MainWindow)
        self.menu_ms_add_map.setObjectName("menu_ms_add_map")
        self.menu_ms_remove_map = QtWidgets.QAction(MainWindow)
        self.menu_ms_remove_map.setObjectName("menu_ms_remove_map")
        self.menu_mr_run_map = QtWidgets.QAction(MainWindow)
        self.menu_mr_run_map.setObjectName("menu_mr_run_map")
        self.menu_mr_clear_map = QtWidgets.QAction(MainWindow)
        self.menu_mr_clear_map.setObjectName("menu_mr_clear_map")
        self.menu_open_stats = QtWidgets.QAction(MainWindow)
        self.menu_open_stats.setObjectName("menu_open_stats")
        self.menu_File.addAction(self.menu_create_new_db)
        self.menu_File.addAction(self.menu_load_db)
        self.menu_File.addAction(self.menu_open_stats)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.menu_exit_app)
        self.menuSettings.addAction(self.menu_preferences)
        self.menu_Help.addAction(self.menu_about)
        self.menu_Edit.addAction(self.menu_ms_add_map)
        self.menu_Edit.addAction(self.menu_ms_add_unlinked_map)
        self.menu_Edit.addAction(self.menu_ms_remove_map)
        self.menu_Edit.addAction(self.menu_mr_run_map)
        self.menu_Edit.addAction(self.menu_mr_clear_map)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Map Watch"))
        self.label.setText(_translate("MainWindow", "Map Selected / Copied:"))
        self.ms_mods.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Map Tier:"))
        self.label_3.setText(_translate("MainWindow", "Item Quantity:"))
        self.label_4.setText(_translate("MainWindow", "Item Rarity:"))
        self.label_5.setText(_translate("MainWindow", "Pack Size:"))
        self.ms_name.setText(_translate("MainWindow", "None"))
        self.ms_add_map.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add this map to drops found from the currently running map listed below.</p></body></html>"))
        self.ms_add_map.setText(_translate("MainWindow", "Add to Map Drops"))
        self.ms_remove_map.setToolTip(_translate("MainWindow", "<html><head/><body><p>Remove the last map added. You may remove more than one with continuous clicks.</p></body></html>"))
        self.ms_remove_map.setText(_translate("MainWindow", "Remove Last Map Added"))
        self.ms_tier.setText(_translate("MainWindow", "0"))
        self.ms_iq.setText(_translate("MainWindow", "0%"))
        self.ms_ir.setText(_translate("MainWindow", "0%"))
        self.ms_pack_size.setText(_translate("MainWindow", "0%"))
        self.label_11.setText(_translate("MainWindow", "Map Rarity:"))
        self.ms_time_stamp.setText(_translate("MainWindow", "00:00:00.00"))
        self.label_13.setText(_translate("MainWindow", "Time Map Last Added:"))
        self.label_6.setText(_translate("MainWindow", "Map Curently Running:"))
        self.mr_mods.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Map Tier:"))
        self.label_8.setText(_translate("MainWindow", "Item Quantity:"))
        self.label_9.setText(_translate("MainWindow", "Item Rarity:"))
        self.label_10.setText(_translate("MainWindow", "Pack Size:"))
        self.mr_name.setText(_translate("MainWindow", "None"))
        self.mr_clear_map.setToolTip(_translate("MainWindow", "<html><head/><body><p>Removes the map currently being run. When set to \'none\' map drops will not be linked to a running map.</p></body></html>"))
        self.mr_clear_map.setText(_translate("MainWindow", "Map Cleared / Remove"))
        self.mr_run_map.setToolTip(_translate("MainWindow", "<html><head/><body><p>Change map currently running to the selected map above.</p></body></html>"))
        self.mr_run_map.setText(_translate("MainWindow", "Run Selected Map (above)"))
        self.mr_ir.setText(_translate("MainWindow", "0%"))
        self.mr_iq.setText(_translate("MainWindow", "0%"))
        self.mr_tier.setText(_translate("MainWindow", "0"))
        self.mr_pack_size.setText(_translate("MainWindow", "0%"))
        self.label_12.setText(_translate("MainWindow", "Map Rarity:"))
        self.label_14.setText(_translate("MainWindow", "Add Bonus Quantity:"))
        self.label_15.setText(_translate("MainWindow", "Add Zana Mod:"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.menu_create_new_db.setText(_translate("MainWindow", "&Create New Map Database"))
        self.menu_load_db.setText(_translate("MainWindow", "&Load Existing Map Database"))
        self.menu_exit_app.setText(_translate("MainWindow", "&Exit"))
        self.menu_preferences.setText(_translate("MainWindow", "&Preferences"))
        self.menu_about.setText(_translate("MainWindow", "&About"))
        self.menu_ms_add_unlinked_map.setText(_translate("MainWindow", "Add Selected Map &Unlinked"))
        self.menu_ms_add_unlinked_map.setToolTip(_translate("MainWindow", "Add to general map drops that are not linked to the currently running map."))
        self.menu_ms_add_map.setText(_translate("MainWindow", "&Add Selected Map"))
        self.menu_ms_remove_map.setText(_translate("MainWindow", "Remove &Last Map"))
        self.menu_mr_run_map.setText(_translate("MainWindow", "&Run Selected Map"))
        self.menu_mr_clear_map.setText(_translate("MainWindow", "Map &Cleared"))
        self.menu_open_stats.setText(_translate("MainWindow", "Open &Statistics File"))

